
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0

    working_directory: ~/learning-map-front

    steps:
      - checkout
      - run:
          name: install dependencies
          command: sudo yarn install

      # run tests!
      - run:
          name: run tests
          command: yarn test

      - run:
          name: run coverage
          command: sudo yarn coverage

      - run:
          name: report coverage
          command: sudo yarn coveralls
  
  deploy:
    docker:
      - image: ubuntu:xenial
    working_directory: ~/learning-map-front
    steps:
      - checkout
      - run:
          name: Copy gcloud service account key
          command: echo ${GOOGLE_AUTH} > ${HOME}/service_account_key.json
      - run:
          name: Run script that deploys to GCP
          command: . ./deploy_develop.sh
      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop

